language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run build

before_deploy:
  - cp ./static_dist/404/index.html ./static_dist/404.html # Move Next-created page to location required by Firebase

deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: firebase
  token:
    secure: hIhx2ytU5B/EoD2f5Sy8w0+sEGyDMkfVYf0oRpqKb3nFaVU0Gmu3HmpDut0gCmyrdjun4QZIdOwmIyGaFRbogfDE/CHofUaxuj2gpchF5f/+kvtZQUMbunbumBbYrOeSZ/r5O8S4aaimMBc0QPHYvRJILJKSCpa4HMQJmi98wa9EHM9EtkSlxRY5EspyFGnBXRdNsbEMKkJfszyuGWmkS+5Is44UV3LmSiyCS79YuaCkUrkB2LEdK1VYIGfwsnF6ixed2wlTu7vTnDLub4bZpy7Pso9ZHih/sRj9hN0voiiEq2hMAizzEYzUdzQH3XAAI3t/x9aZywgA+VHcZYZzxIogxD5ihf72l393inY4KuNa4pBxdGstXjALEG1q0i/V6bLjjhti2s7ygX3cxRVIorCt3JGHwzu0odZjtN2Djl94zZBc7gWrqn/7HcDT2ON10ToG7nenMUR5+YHdcgJbPhPys+okvPK7UWcxaAL6exp23sR0c5q27a5G63UAhuikbH2mdhUbDa+ThjmH2ROfwgcGBxBgiOu4rWtVXoSAvlbk3cP7BbgGVFTFD8PPe0djjVCKWpnxgY2UI0E4Gb02zOiqgwSxMDCcPtFmiByhyZ7hWZSSICVXCtj/NilcdQqZB5qU9TG+VTXgqs+4HRinmqfmHulzbEMSXeIcXVNnL+k=
